remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 🚗 World Road Safety Analysis - Power BI Report 📊
description: What does the data tells us about creating safer roads for all?

header: |
  <style>
    h1 { font-size: 10px !important; }
  </style>
